/**
 * The checkout fixture app shell.
 *
 * Boots a buyer wallet via the mock embedded-wallet seam (a browser test has no
 * extension), wires `<AgencProvider>` with that signer (write client) + a gPA
 * read transport over the sandbox RPC, and mounts `<CheckoutFlow>`.
 *
 * The buyer keypair is GENERATED BY THE HARNESS (Node) and injected here via
 * `/sandbox-config.json` `buyerSecretKeyHex` — the mock wallet ADOPTS it
 * (`createMockEmbeddedWallet({ secretKeyBytes })`). That way the harness already
 * holds the buyer secret it needs to sign the worker-side `set_task_job_spec`
 * (the buyer is the task creator), and the browser and harness share one buyer
 * identity. This is a TEST FIXTURE — sharing the key with the local harness is
 * intentional and scoped to the local sandbox.
 *
 * Runtime config is fetched from `/sandbox-config.json` (written by the Playwright
 * global-setup from the live sandbox env + fixtures), so the same built app runs
 * against whatever the validator was seeded with.
 */
import { useEffect, useMemo, useState } from "react";
import { createSolanaRpc } from "@solana/kit";
import { createMarketplaceClient } from "@tetsuo-ai/marketplace-sdk";
import {
  AgencProvider,
  createReadTransport,
  signerFromEmbeddedWallet,
  type AgencProviderConfig,
  type TransactionSigner,
} from "@tetsuo-ai/marketplace-react";
// The test-only MOCK lives behind the ./testing subpath, not the root barrel.
import { createMockEmbeddedWallet } from "@tetsuo-ai/marketplace-react/testing";
import { CheckoutFlow, type CheckoutConfig } from "./CheckoutFlow";

interface SandboxConfig extends CheckoutConfig {
  rpcUrl: string;
  /** 64-byte buyer secret (hex), generated by the harness and adopted here. */
  buyerSecretKeyHex: string;
}

declare global {
  interface Window {
    __checkout?: {
      buyerAddress: string;
      taskPda: string | null;
      workerReady: boolean;
      accepted: boolean;
      error: string | null;
    };
  }
}

function hexToBytes(hex: string): Uint8Array {
  const clean = hex.startsWith("0x") ? hex.slice(2) : hex;
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i += 1) {
    out[i] = Number.parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

export function App() {
  const [sandbox, setSandbox] = useState<SandboxConfig | null>(null);
  const [signer, setSigner] = useState<TransactionSigner | null>(null);

  // Load the live sandbox config + adopt the harness-provided buyer wallet.
  useEffect(() => {
    let cancelled = false;
    (async () => {
      const res = await fetch("/sandbox-config.json", { cache: "no-store" });
      const cfg = (await res.json()) as SandboxConfig;
      const conn = await createMockEmbeddedWallet({
        secretKeyBytes: hexToBytes(cfg.buyerSecretKeyHex),
      }).connect();
      if (cancelled) return;
      setSandbox(cfg);
      setSigner(signerFromEmbeddedWallet(conn));
      window.__checkout = {
        buyerAddress: String(conn.address),
        taskPda: null,
        workerReady: false,
        accepted: false,
        error: null,
      };
    })().catch((e) => {
      if (typeof window !== "undefined") {
        window.__checkout = {
          buyerAddress: "",
          taskPda: null,
          workerReady: false,
          accepted: false,
          error: String(e),
        };
      }
    });
    return () => {
      cancelled = true;
    };
  }, []);

  const providerConfig = useMemo<AgencProviderConfig | null>(() => {
    if (!sandbox || !signer) return null;
    // Build the write client over the kit RPC WITHOUT rpcSubscriptions, so the
    // SDK confirms via getSignatureStatuses POLLING instead of a ws:// channel.
    // solana-test-validator's PubSub (ws://…:8900) is not reliably reachable
    // from a headless-browser origin, so a WS-confirming client hangs with
    // "WebSocket failed to connect". The `client` override is the same public
    // seam startLocalMarketplace().client uses; reads still go through the gPA
    // queryTransport over the same RPC.
    const client = createMarketplaceClient({
      rpc: createSolanaRpc(sandbox.rpcUrl),
      signer,
    });
    return {
      network: "localnet",
      client,
      queryTransport: createReadTransport({
        rpc: createSolanaRpc(sandbox.rpcUrl),
      }),
    };
  }, [sandbox, signer]);

  if (!sandbox || !providerConfig) {
    return <p data-testid="booting">booting checkout fixture…</p>;
  }

  // The browser cannot run the Node SDK worker side; it publishes the task PDA
  // and waits for the harness to flip window.__checkout.workerReady.
  const onHired = async (taskPda: string) => {
    if (window.__checkout) window.__checkout.taskPda = taskPda;
    const deadline = Date.now() + 120_000;
    while (Date.now() < deadline) {
      if (window.__checkout?.workerReady) return;
      await new Promise((r) => setTimeout(r, 200));
    }
    throw new Error("timed out waiting for the worker harness (workerReady)");
  };

  return (
    <AgencProvider config={providerConfig}>
      <main style={{ fontFamily: "system-ui", padding: "2rem", maxWidth: 640 }}>
        <h1>AgenC checkout fixture</h1>
        <p data-testid="buyer-address">{String(window.__checkout?.buyerAddress ?? "")}</p>
        <AcceptedBridge />
        <CheckoutFlow config={sandbox} onHired={onHired} />
      </main>
    </AgencProvider>
  );
}

/**
 * Mirrors the accept-signature DOM node onto window.__checkout.accepted so the
 * Node harness has a single boolean to await.
 */
function AcceptedBridge() {
  useEffect(() => {
    const id = setInterval(() => {
      const sig = document.querySelector('[data-testid="accept-signature"]');
      if (sig && window.__checkout) window.__checkout.accepted = true;
    }, 150);
    return () => clearInterval(id);
  }, []);
  return null;
}
