// Codama codegen: Anchor IDL -> @solana/kit TypeScript client (src/generated/).
// AUTOGENERATED output — never hand-edit files under src/generated/.
// Loop-0 spike: proves Codama digests the agenc-coordination Anchor 0.32.1 IDL.
import {
  cpSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createFromRoot, updateInstructionsVisitor } from "codama";
import { rootNodeFromAnchor } from "@codama/nodes-from-anchor";
import * as renderers from "@codama/renderers-js";
import { format } from "prettier";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, "../../..");
const OUT = path.join(__dirname, "../src/generated");
const IDL_PATH = path.join(
  REPO,
  "artifacts/anchor/idl/agenc_coordination.json",
);

const BORSH_STRING_CODEC = `/**
 * This code was AUTOGENERATED by scripts/generate.mjs. Please DO NOT EDIT
 * this file; rerun \`npm run sdk:generate\` to update generated codecs.
 */

import {
  createDecoder,
  createEncoder,
  type VariableSizeDecoder,
  type VariableSizeEncoder,
} from "@solana/kit";

function assertWellFormedUnicode(value: string): void {
  for (let index = 0; index < value.length; index += 1) {
    const codeUnit = value.charCodeAt(index);
    if (codeUnit >= 0xd800 && codeUnit <= 0xdbff) {
      const next = value.charCodeAt(index + 1);
      if (!(next >= 0xdc00 && next <= 0xdfff)) {
        throw new TypeError(
          "Borsh string contains an unpaired high surrogate at UTF-16 index " +
            index,
        );
      }
      index += 1;
    } else if (codeUnit >= 0xdc00 && codeUnit <= 0xdfff) {
      throw new TypeError(
        "Borsh string contains an unpaired low surrogate at UTF-16 index " +
          index,
      );
    }
  }
}

/**
 * Encode only well-formed Unicode scalar text to Rust-compatible UTF-8.
 *
 * JavaScript permits lone UTF-16 surrogates, but Rust \`String\` does not.
 * TextEncoder silently replaces a lone surrogate with U+FFFD, which would make
 * distinct SDK inputs produce the same on-chain bytes. Reject those inputs
 * before encoding instead.
 */
export function getBorshStringEncoder(): VariableSizeEncoder<string> {
  let textEncoder: TextEncoder | undefined;
  const encode = (value: string): Uint8Array => {
    assertWellFormedUnicode(value);
    textEncoder ??= new TextEncoder();
    return textEncoder.encode(value);
  };
  return createEncoder({
    getSizeFromValue: (value) => encode(value).length,
    write(value, bytes, offset) {
      const encoded = encode(value);
      bytes.set(encoded, offset);
      return offset + encoded.length;
    },
  });
}

/**
 * Decode the exact UTF-8 byte sequence accepted by Rust's Borsh \`String\`.
 *
 * Kit's general-purpose UTF-8 decoder normalizes decoded strings by removing
 * U+0000 and the platform TextDecoder strips a leading U+FEFF by default.
 * Neither transformation is valid for a Borsh \`String\`: both code points are
 * ordinary Rust \`String\` contents. Invalid UTF-8 must also fail instead of
 * being replaced with U+FFFD, matching Borsh's Rust deserializer.
 */
export function getBorshStringDecoder(): VariableSizeDecoder<string> {
  let textDecoder: TextDecoder | undefined;
  return createDecoder({
    read(bytes, offset) {
      textDecoder ??= new TextDecoder("utf-8", {
        fatal: true,
        // Despite its name, true means "do not consume the BOM".
        ignoreBOM: true,
      });
      return [textDecoder.decode(bytes.subarray(offset)), bytes.length];
    },
  });
}
`;

function generatedTypeScriptFiles(directory) {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) return generatedTypeScriptFiles(absolute);
    return entry.isFile() && entry.name.endsWith(".ts") ? [absolute] : [];
  });
}

/**
 * Codama currently renders IDL \`string\` nodes with Kit's normalizing UTF-8
 * codecs. Rewrite that renderer output at generation time so every account and
 * instruction uses byte-faithful Borsh string codecs. The companion event
 * emitter selects the same decoder directly (see generate-events.mjs).
 */
async function installBorshStringCodecs() {
  const codecsDirectory = path.join(OUT, "codecs");
  const codecPath = path.join(codecsDirectory, "borshString.ts");
  mkdirSync(codecsDirectory, { recursive: true });
  writeFileSync(
    codecPath,
    await format(BORSH_STRING_CODEC, { filepath: codecPath }),
  );

  let rewrittenFiles = 0;
  let rewrittenDecoderCalls = 0;
  let rewrittenEncoderCalls = 0;
  for (const file of generatedTypeScriptFiles(OUT)) {
    if (file === codecPath) continue;
    let source = readFileSync(file, "utf8");
    const decoderCalls = source.match(/getUtf8Decoder\(\)/g)?.length ?? 0;
    const encoderCalls = source.match(/getUtf8Encoder\(\)/g)?.length ?? 0;
    if (decoderCalls === 0 && encoderCalls === 0) continue;

    const localImports = [];
    for (const [kitName, localName, calls] of [
      ["getUtf8Decoder", "getBorshStringDecoder", decoderCalls],
      ["getUtf8Encoder", "getBorshStringEncoder", encoderCalls],
    ]) {
      if (calls === 0) continue;
      const kitImport = `  ${kitName},\n`;
      if (!source.includes(kitImport)) {
        throw new Error(
          `Cannot replace Codama ${kitName} import in ${path.relative(REPO, file)}`,
        );
      }
      source = source.replace(kitImport, "");
      source = source.replaceAll(`${kitName}()`, `${localName}()`);
      localImports.push(localName);
    }

    const kitImportEnd = '} from "@solana/kit";';
    if (!source.includes(kitImportEnd)) {
      throw new Error(
        `Cannot add Borsh string codec import in ${path.relative(REPO, file)}`,
      );
    }
    let relativeCodec = path
      .relative(path.dirname(file), codecPath)
      .replaceAll(path.sep, "/")
      .replace(/\.ts$/, "");
    if (!relativeCodec.startsWith(".")) relativeCodec = `./${relativeCodec}`;
    source = source.replace(
      kitImportEnd,
      `${kitImportEnd}\n\nimport { ${localImports.join(", ")} } from "${relativeCodec}";`,
    );
    if (/\bgetUtf8(?:Decoder|Encoder)\b/.test(source)) {
      throw new Error(
        `Incomplete Codama UTF-8 codec replacement in ${path.relative(REPO, file)}`,
      );
    }
    writeFileSync(file, await format(source, { filepath: file }));
    rewrittenFiles += 1;
    rewrittenDecoderCalls += decoderCalls;
    rewrittenEncoderCalls += encoderCalls;
  }

  console.log(
    `OK — installed Borsh string codecs in ${rewrittenFiles} generated modules ` +
      `(${rewrittenEncoderCalls} encoder / ${rewrittenDecoderCalls} decoder sites)`,
  );
}

const idl = JSON.parse(readFileSync(IDL_PATH, "utf8"));
console.log(
  "IDL:",
  idl.metadata?.name ?? idl.name,
  "| instructions:",
  idl.instructions.length,
  "| accounts:",
  (idl.accounts ?? []).length,
  "| types:",
  (idl.types ?? []).length,
);

// @codama/renderers-js exposes the kit renderer; the exact export name has varied
// across versions (renderVisitor / renderJavaScriptVisitor). Resolve whichever exists.
const renderVisitor =
  renderers.renderVisitor ??
  renderers.renderJavaScriptVisitor ??
  renderers.default?.renderVisitor;
if (typeof renderVisitor !== "function") {
  throw new Error(
    "Could not find a render visitor in @codama/renderers-js. Exports: " +
      Object.keys(renderers).join(", "),
  );
}

// renderVisitor scaffolds a whole standalone package (package.json + src/generated/…).
// We only want the client modules, flattened directly under our src/generated/.
const tmp = mkdtempSync(path.join(tmpdir(), "codama-"));
const codama = createFromRoot(rootNodeFromAnchor(idl));

// cancelTask.agentStats is the only AgentStats handler whose PDA is seeded on an
// OPTIONAL account (`creator_agent`, which the creator may omit). Codama's resolver
// refuses to auto-derive a PDA whose seed references an optional account
// (CANNOT_USE_OPTIONAL_ACCOUNT_AS_PDA_SEED_VALUE), so we strip the auto-derivation
// for THIS account only and require the caller to pass the address explicitly.
//
// This does NOT weaken validation: the Anchor program still pins
// `agent_stats = ["agent_stats", creator_agent]` via its `seeds`/`bump` constraint
// on-chain, so a wrong key is rejected by the program regardless of what the client
// passes. The facade re-derives the canonical PDA (findAgentStatsPda) and supplies it,
// preserving lazy init-on-first-write. The other four AgentStats handlers seed on a
// non-optional account/field and are auto-derived by codama unchanged.
codama.update(
  updateInstructionsVisitor({
    cancelTask: {
      accounts: {
        agentStats: { defaultValue: null },
      },
    },
    // record_*_moderation.moderation_attestor (P6.8) is an OPTIONAL roster account whose
    // on-chain `["moderation_attestor", moderator]` PDA exists ONLY when a deputy attestor
    // is registered. The default path (the global moderation authority records directly)
    // has NO such account, so auto-deriving it makes the async builder pass a non-existent
    // address that the program rejects (AccountNotInitialized). Strip the auto-derivation
    // so an omitted attestor renders as the program-ID placeholder — Anchor's `Option`
    // convention reads that as `None` and runs the global-authority branch. The Anchor
    // program still pins the canonical PDA + `attestor == moderator` when a deputy DOES
    // pass one, so the deputy path stays fully validated; the caller (or the facade) just
    // supplies the address explicitly for that branch.
    recordTaskModeration: {
      accounts: {
        moderationAttestor: { defaultValue: null },
      },
    },
    recordListingModeration: {
      accounts: {
        moderationAttestor: { defaultValue: null },
      },
    },
  }),
);

await codama.accept(renderVisitor(tmp));
const inner = path.join(tmp, "src", "generated");
rmSync(OUT, { recursive: true, force: true });
cpSync(inner, OUT, { recursive: true });
rmSync(tmp, { recursive: true, force: true });
await installBorshStringCodecs();
console.log("OK — generated @solana/kit client into", path.relative(REPO, OUT));

// Event codecs: Codama tree-shakes IDL events (nothing in the rendered client
// references them), so a companion emitter renders src/generated/events/ from
// the same IDL and appends its export to the generated barrel. Running it here
// keeps `npm run sdk:drift` (regen + git diff src/generated) covering event
// codecs automatically.
const { generateEvents } = await import("./generate-events.mjs");
await generateEvents();
