// Event codec emitter: Anchor IDL events -> src/generated/events/ (@solana/kit decoders).
//
// Codama tree-shakes IDL events (nothing in the rendered client references them), so
// `scripts/generate.mjs` renders ZERO event codecs. This companion emitter reads the
// same IDL and renders generated-style decoder modules for every event, plus the
// `AgencEvent` discriminated union and the `AGENC_EVENT_DECODERS` discriminator table
// that `src/events/` (the hand-written runtime layer) keys off.
//
// Invariants this emitter relies on (verified against the current IDL and enforced
// below with hard throws so IDL drift fails generation loudly instead of silently
// emitting wrong codecs):
//   - every `idl.events[]` name has a matching struct entry in `idl.types[]`
//   - event struct fields use ONLY primitives (u8..u128, i8..i128, bool), pubkey,
//     string, fixed arrays { array: [inner, N] }, { option: inner }, and
//     { defined: { name } } references to FIELDLESS (C-style) enums — which reuse
//     the Codama-generated getXDecoder() from ../types (NO data-carrying variants,
//     NO vecs)
//
// Output is deterministic (events sorted by name, fixed formatting, no timestamps),
// so `npm run sdk:drift` (regenerate + `git diff src/generated`) covers event codecs.
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, "../../..");
const OUT = path.join(__dirname, "../src/generated");
const EVENTS_OUT = path.join(OUT, "events");
const IDL_PATH = path.join(REPO, "artifacts/anchor/idl/agenc_coordination.json");

const HEADER = `/**
 * This code was AUTOGENERATED by scripts/generate-events.mjs (event codecs that
 * the Codama renderer tree-shakes away). Please DO NOT EDIT THIS FILE, instead
 * rerun \`npm run sdk:generate\` to update it.
 */`;

// ---------------------------------------------------------------------------
// naming helpers (match Codama's naming conventions)
// ---------------------------------------------------------------------------

/** PascalCase -> camelCase ("TaskCreated" -> "taskCreated"). */
function camelCase(name) {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

/** snake_case -> camelCase ("task_id" -> "taskId"). */
function fieldCamelCase(name) {
  return name.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

/** PascalCase -> CONST_CASE ("TaskCreated" -> "TASK_CREATED"). */
function constCase(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .toUpperCase();
}

/** 8-byte discriminator -> lowercase hex key. */
function discriminatorHex(bytes) {
  return bytes.map((b) => b.toString(16).padStart(2, "0")).join("");
}

// ---------------------------------------------------------------------------
// IDL type -> { tsType, decoderExpr } mapping
// ---------------------------------------------------------------------------

// [tsType, decoderExpr, value imports]
const PRIMITIVES = {
  u8: ["number", "getU8Decoder()", ["getU8Decoder"]],
  u16: ["number", "getU16Decoder()", ["getU16Decoder"]],
  u32: ["number", "getU32Decoder()", ["getU32Decoder"]],
  u64: ["bigint", "getU64Decoder()", ["getU64Decoder"]],
  u128: ["bigint", "getU128Decoder()", ["getU128Decoder"]],
  i8: ["number", "getI8Decoder()", ["getI8Decoder"]],
  i16: ["number", "getI16Decoder()", ["getI16Decoder"]],
  i32: ["number", "getI32Decoder()", ["getI32Decoder"]],
  i64: ["bigint", "getI64Decoder()", ["getI64Decoder"]],
  i128: ["bigint", "getI128Decoder()", ["getI128Decoder"]],
  bool: ["boolean", "getBooleanDecoder()", ["getBooleanDecoder"]],
};

/**
 * Maps one IDL field type to TypeScript type + @solana/kit decoder expression.
 * Records required @solana/kit imports on `imports` ({ values: Set, types: Set }).
 *
 * `typesByName` is the IDL `types[]` lookup; it is only consulted for `{ defined }`
 * references, and only fieldless (C-style) enums are supported — those round-trip
 * through the Codama-generated `getXDecoder()` in `../types`, recorded on
 * `definedImports` so the event file imports the canonical generated codec rather
 * than re-deriving it (single source of truth, drift-safe).
 */
function mapType(idlType, imports, context, typesByName, definedImports) {
  if (typeof idlType === "string") {
    const prim = PRIMITIVES[idlType];
    if (prim) {
      for (const v of prim[2]) imports.values.add(v);
      return { tsType: prim[0], decoderExpr: prim[1] };
    }
    if (idlType === "pubkey") {
      imports.values.add("getAddressDecoder");
      imports.types.add("Address");
      return { tsType: "Address", decoderExpr: "getAddressDecoder()" };
    }
    if (idlType === "string") {
      imports.values.add("addDecoderSizePrefix");
      imports.values.add("getUtf8Decoder");
      imports.values.add("getU32Decoder");
      return {
        tsType: "string",
        decoderExpr: "addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())",
      };
    }
    throw new Error(`Unsupported primitive event field type in ${context}: ${idlType}`);
  }
  if (idlType !== null && typeof idlType === "object") {
    if (Array.isArray(idlType.array)) {
      const [inner, size] = idlType.array;
      if (typeof size !== "number") {
        throw new Error(`Unsupported non-literal array size in ${context}`);
      }
      if (inner === "u8") {
        imports.values.add("fixDecoderSize");
        imports.values.add("getBytesDecoder");
        imports.types.add("ReadonlyUint8Array");
        return {
          tsType: "ReadonlyUint8Array",
          decoderExpr: `fixDecoderSize(getBytesDecoder(), ${size})`,
        };
      }
      const innerMapped = mapType(inner, imports, context, typesByName, definedImports);
      imports.values.add("getArrayDecoder");
      return {
        tsType: `Array<${innerMapped.tsType}>`,
        decoderExpr: `getArrayDecoder(${innerMapped.decoderExpr}, { size: ${size} })`,
      };
    }
    if (idlType.option !== undefined) {
      const innerMapped = mapType(idlType.option, imports, context, typesByName, definedImports);
      imports.values.add("getOptionDecoder");
      imports.types.add("Option");
      return {
        tsType: `Option<${innerMapped.tsType}>`,
        decoderExpr: `getOptionDecoder(${innerMapped.decoderExpr})`,
      };
    }
    if (idlType.defined && typeof idlType.defined.name === "string") {
      const definedName = idlType.defined.name;
      const definedType = typesByName?.get(definedName);
      if (!definedType || definedType.type?.kind !== "enum") {
        throw new Error(
          `Unsupported defined event field type in ${context}: "${definedName}" ` +
            "(generate-events.mjs only resolves defined references to fieldless enums)",
        );
      }
      // Only fieldless (C-style / scalar) enum variants round-trip through the
      // Codama-generated getEnumDecoder. A data-carrying variant would need the
      // full discriminated-union codec — reject it loudly instead of emitting a
      // wrong codec.
      const variants = definedType.type.variants ?? [];
      const hasFields = variants.some(
        (v) => v.fields !== undefined && v.fields !== null,
      );
      if (hasFields) {
        throw new Error(
          `Unsupported defined event field type in ${context}: "${definedName}" ` +
            "has data-carrying variants (only fieldless enums are supported)",
        );
      }
      // Reuse the canonical Codama-generated codec from ../types so the event
      // payload decodes identically to the rest of the SDK (no drift).
      definedImports.values.add(`get${definedName}Decoder`);
      definedImports.types.add(definedName);
      return {
        tsType: definedName,
        decoderExpr: `get${definedName}Decoder()`,
      };
    }
  }
  throw new Error(
    `Unsupported event field type in ${context}: ${JSON.stringify(idlType)} ` +
      "(generate-events.mjs only supports primitives, pubkey, string, fixed arrays, options, and fieldless defined enums)",
  );
}

// ---------------------------------------------------------------------------
// renderers
// ---------------------------------------------------------------------------

function renderDocs(docs, indent) {
  if (!docs || docs.length === 0) return "";
  if (docs.length === 1) return `${indent}/** ${docs[0]} */\n`;
  return `${indent}/**\n${docs.map((d) => `${indent} * ${d}`).join("\n")}\n${indent} */\n`;
}

function renderImports(imports) {
  const names = [
    ...[...imports.values].sort(),
    ...[...imports.types].sort().map((t) => `type ${t}`),
  ];
  return `import {\n${names.map((n) => `  ${n},`).join("\n")}\n} from "@solana/kit";`;
}

/**
 * Renders the `../types` import block for Codama-generated defined-type codecs
 * referenced by an event (returns "" when none are used).
 */
function renderDefinedImports(definedImports) {
  if (definedImports.values.size === 0 && definedImports.types.size === 0) return "";
  const names = [
    ...[...definedImports.values].sort(),
    ...[...definedImports.types].sort().map((t) => `type ${t}`),
  ];
  return `\nimport {\n${names.map((n) => `  ${n},`).join("\n")}\n} from "../types";`;
}

/** Renders src/generated/events/<camelName>.ts for one event. */
function renderEventFile(event, typesByName) {
  const { name, discriminator, docs, fields } = event;
  const imports = { values: new Set(["getStructDecoder"]), types: new Set(["Decoder", "ReadonlyUint8Array"]) };
  const definedImports = { values: new Set(), types: new Set() };
  const mappedFields = fields.map((f) => ({
    name: fieldCamelCase(f.name),
    docs: f.docs ?? [],
    ...mapType(f.type, imports, `${name}.${f.name}`, typesByName, definedImports),
  }));

  const typeFields = mappedFields
    .map((f) => `${renderDocs(f.docs, "  ")}  ${f.name}: ${f.tsType};`)
    .join("\n");
  const decoderFields = mappedFields
    .map((f) => `    ["${f.name}", ${f.decoderExpr}],`)
    .join("\n");

  return `${HEADER}

${renderImports(imports)}${renderDefinedImports(definedImports)}

/** 8-byte Anchor event discriminator for \`${name}\` (sha256("event:${name}")[0..8]). */
export const ${constCase(name)}_EVENT_DISCRIMINATOR: ReadonlyUint8Array = new Uint8Array([
  ${discriminator.join(", ")},
]);

${renderDocs(docs, "")}export type ${name}EventData = {
${typeFields}
};

/**
 * Gets the decoder for the {@link ${name}EventData} event payload — the bytes
 * AFTER the 8-byte \`${constCase(name)}_EVENT_DISCRIMINATOR\`.
 */
export function get${name}EventDecoder(): Decoder<${name}EventData> {
  return getStructDecoder([
${decoderFields}
  ]);
}
`;
}

/** Renders src/generated/events/agencEvent.ts (union + discriminator table). */
function renderUnionFile(events) {
  const imports = events
    .map(
      (e) =>
        `import {\n  get${e.name}EventDecoder,\n  type ${e.name}EventData,\n} from "./${camelCase(e.name)}";`,
    )
    .join("\n");

  const unionMembers = events
    .map((e) => `  | { eventName: "${e.name}"; data: ${e.name}EventData }`)
    .join("\n");

  const tableEntries = events
    .map((e) => {
      const hex = discriminatorHex(e.discriminator);
      return `  "${hex}": {
    eventName: "${e.name}",
    decode: (payload) => ({
      eventName: "${e.name}",
      data: get${e.name}EventDecoder().decode(payload),
    }),
  },`;
    })
    .join("\n");

  return `${HEADER}

import { type ReadonlyUint8Array } from "@solana/kit";

${imports}

/**
 * Discriminated union over every event emitted by the agenc-coordination
 * program, tagged by \`eventName\`. Narrow on \`eventName\` to get the typed
 * payload:
 *
 * \`\`\`ts
 * if (event.eventName === "TaskCreated") {
 *   console.log(event.data.rewardAmount); // bigint
 * }
 * \`\`\`
 */
export type AgencEvent =
${unionMembers};

/** The name of any agenc-coordination program event. */
export type AgencEventName = AgencEvent["eventName"];

/** One entry of {@link AGENC_EVENT_DECODERS}. */
export type AgencEventDecoderEntry = {
  readonly eventName: AgencEventName;
  /**
   * Decodes an event payload — the bytes AFTER the 8-byte discriminator —
   * into a tagged {@link AgencEvent}.
   */
  readonly decode: (payload: ReadonlyUint8Array) => AgencEvent;
};

/**
 * Event decoder lookup keyed by the LOWERCASE HEX of the 8-byte Anchor event
 * discriminator (the first 8 bytes of the base64 \`Program data:\` log blob).
 */
export const AGENC_EVENT_DECODERS: {
  readonly [discriminatorHex: string]: AgencEventDecoderEntry;
} = {
${tableEntries}
};
`;
}

/** Renders src/generated/events/index.ts (barrel). */
function renderBarrel(events) {
  const lines = [
    'export * from "./agencEvent";',
    ...events.map((e) => `export * from "./${camelCase(e.name)}";`),
  ];
  return `${HEADER}\n\n${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

/**
 * Renders src/generated/events/ from the IDL and appends the events barrel
 * export to the Codama-written src/generated/index.ts (idempotent).
 */
export async function generateEvents() {
  const idl = JSON.parse(readFileSync(IDL_PATH, "utf8"));
  const typesByName = new Map((idl.types ?? []).map((t) => [t.name, t]));

  const events = [...(idl.events ?? [])]
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
    .map((event) => {
      const struct = typesByName.get(event.name);
      if (!struct || struct.type?.kind !== "struct") {
        throw new Error(`IDL event ${event.name} has no matching struct in idl.types`);
      }
      if (!Array.isArray(event.discriminator) || event.discriminator.length !== 8) {
        throw new Error(`IDL event ${event.name} has no 8-byte discriminator`);
      }
      return {
        name: event.name,
        discriminator: event.discriminator,
        docs: struct.docs ?? [],
        fields: struct.type.fields ?? [],
      };
    });

  // Duplicate discriminators would make the lookup table silently drop events.
  const seenDiscriminators = new Map();
  for (const e of events) {
    const hex = discriminatorHex(e.discriminator);
    if (seenDiscriminators.has(hex)) {
      throw new Error(
        `Duplicate event discriminator ${hex}: ${seenDiscriminators.get(hex)} vs ${e.name}`,
      );
    }
    seenDiscriminators.set(hex, e.name);
  }

  rmSync(EVENTS_OUT, { recursive: true, force: true });
  mkdirSync(EVENTS_OUT, { recursive: true });
  for (const event of events) {
    writeFileSync(
      path.join(EVENTS_OUT, `${camelCase(event.name)}.ts`),
      renderEventFile(event, typesByName),
    );
  }
  writeFileSync(path.join(EVENTS_OUT, "agencEvent.ts"), renderUnionFile(events));
  writeFileSync(path.join(EVENTS_OUT, "index.ts"), renderBarrel(events));

  // Append the events export to the Codama barrel (idempotent; generate.mjs
  // rewrites the barrel each run, so this re-appends after every regen).
  const barrelPath = path.join(OUT, "index.ts");
  const exportLine = 'export * from "./events/index.js";';
  let barrel = readFileSync(barrelPath, "utf8");
  if (!barrel.includes(exportLine)) {
    if (!barrel.endsWith("\n")) barrel += "\n";
    writeFileSync(barrelPath, barrel + exportLine + "\n");
  }

  console.log(`OK — generated ${events.length} event codecs into src/generated/events/`);
}

const isMain =
  process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  await generateEvents();
}
