// Codama codegen: Anchor IDL -> @solana/kit TypeScript client (src/generated/).
// AUTOGENERATED output — never hand-edit files under src/generated/.
// Loop-0 spike: proves Codama digests the agenc-coordination Anchor 0.32.1 IDL.
import { readFileSync, rmSync, cpSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { createFromRoot } from "codama";
import { rootNodeFromAnchor } from "@codama/nodes-from-anchor";
import * as renderers from "@codama/renderers-js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(__dirname, "../../..");
const OUT = path.join(__dirname, "../src/generated");
const IDL_PATH = path.join(REPO, "artifacts/anchor/idl/agenc_coordination.json");

const idl = JSON.parse(readFileSync(IDL_PATH, "utf8"));
console.log(
  "IDL:",
  idl.metadata?.name ?? idl.name,
  "| instructions:",
  idl.instructions.length,
  "| accounts:",
  (idl.accounts ?? []).length,
  "| types:",
  (idl.types ?? []).length,
);

// @codama/renderers-js exposes the kit renderer; the exact export name has varied
// across versions (renderVisitor / renderJavaScriptVisitor). Resolve whichever exists.
const renderVisitor =
  renderers.renderVisitor ??
  renderers.renderJavaScriptVisitor ??
  renderers.default?.renderVisitor;
if (typeof renderVisitor !== "function") {
  throw new Error(
    "Could not find a render visitor in @codama/renderers-js. Exports: " +
      Object.keys(renderers).join(", "),
  );
}

// renderVisitor scaffolds a whole standalone package (package.json + src/generated/…).
// We only want the client modules, flattened directly under our src/generated/.
const tmp = mkdtempSync(path.join(tmpdir(), "codama-"));
const codama = createFromRoot(rootNodeFromAnchor(idl));
await codama.accept(renderVisitor(tmp));
const inner = path.join(tmp, "src", "generated");
rmSync(OUT, { recursive: true, force: true });
cpSync(inner, OUT, { recursive: true });
rmSync(tmp, { recursive: true, force: true });
console.log("OK — generated @solana/kit client into", path.relative(REPO, OUT));
